/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_component,
	claim_element,
	claim_space,
	claim_text,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from '../web_modules/svelte/internal/index.mjs';

import Breadcrumbs from '../components/breadcrumbs.js';

function create_fragment(ctx) {
	let main;
	let breadcrumbs;
	let t0;
	let section;
	let div11;
	let div10;
	let div6;
	let div5;
	let div3;
	let div0;
	let img0;
	let img0_src_value;
	let t1;
	let div1;
	let img1;
	let img1_src_value;
	let t2;
	let div2;
	let img2;
	let img2_src_value;
	let t3;
	let div4;
	let t4;
	let div9;
	let div7;
	let h3;
	let t5;
	let t6;
	let ul;
	let li0;
	let strong0;
	let t7;
	let t8;
	let t9;
	let li1;
	let strong1;
	let t10;
	let t11;
	let t12;
	let li2;
	let strong2;
	let t13;
	let t14;
	let t15;
	let li3;
	let strong3;
	let t16;
	let t17;
	let a;
	let t18;
	let t19;
	let div8;
	let h2;
	let t20;
	let t21;
	let p;
	let t22;
	let current;
	breadcrumbs = new Breadcrumbs({});

	return {
		c() {
			main = element("main");
			create_component(breadcrumbs.$$.fragment);
			t0 = space();
			section = element("section");
			div11 = element("div");
			div10 = element("div");
			div6 = element("div");
			div5 = element("div");
			div3 = element("div");
			div0 = element("div");
			img0 = element("img");
			t1 = space();
			div1 = element("div");
			img1 = element("img");
			t2 = space();
			div2 = element("div");
			img2 = element("img");
			t3 = space();
			div4 = element("div");
			t4 = space();
			div9 = element("div");
			div7 = element("div");
			h3 = element("h3");
			t5 = text(/*title*/ ctx[0]);
			t6 = space();
			ul = element("ul");
			li0 = element("li");
			strong0 = element("strong");
			t7 = text("Category");
			t8 = text(": Web design");
			t9 = space();
			li1 = element("li");
			strong1 = element("strong");
			t10 = text("Client");
			t11 = text(": ASU Company");
			t12 = space();
			li2 = element("li");
			strong2 = element("strong");
			t13 = text("Project date");
			t14 = text(": 01 March, 2020");
			t15 = space();
			li3 = element("li");
			strong3 = element("strong");
			t16 = text("Project URL");
			t17 = text(": ");
			a = element("a");
			t18 = text("www.example.com");
			t19 = space();
			div8 = element("div");
			h2 = element("h2");
			t20 = text("This is an example of portfolio detail");
			t21 = space();
			p = element("p");
			t22 = text("Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.");
			this.h();
		},
		l(nodes) {
			main = claim_element(nodes, "MAIN", {});
			var main_nodes = children(main);
			claim_component(breadcrumbs.$$.fragment, main_nodes);
			t0 = claim_space(main_nodes);
			section = claim_element(main_nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div11 = claim_element(section_nodes, "DIV", { class: true });
			var div11_nodes = children(div11);
			div10 = claim_element(div11_nodes, "DIV", { class: true });
			var div10_nodes = children(div10);
			div6 = claim_element(div10_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			div5 = claim_element(div6_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div3 = claim_element(div5_nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			div0 = claim_element(div3_nodes, "DIV", { class: true });
			var div0_nodes = children(div0);
			img0 = claim_element(div0_nodes, "IMG", { src: true, alt: true });
			div0_nodes.forEach(detach);
			t1 = claim_space(div3_nodes);
			div1 = claim_element(div3_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			img1 = claim_element(div1_nodes, "IMG", { src: true, alt: true });
			div1_nodes.forEach(detach);
			t2 = claim_space(div3_nodes);
			div2 = claim_element(div3_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			img2 = claim_element(div2_nodes, "IMG", { src: true, alt: true });
			div2_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t3 = claim_space(div5_nodes);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			children(div4).forEach(detach);
			div5_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			t4 = claim_space(div10_nodes);
			div9 = claim_element(div10_nodes, "DIV", { class: true });
			var div9_nodes = children(div9);
			div7 = claim_element(div9_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			h3 = claim_element(div7_nodes, "H3", {});
			var h3_nodes = children(h3);
			t5 = claim_text(h3_nodes, /*title*/ ctx[0]);
			h3_nodes.forEach(detach);
			t6 = claim_space(div7_nodes);
			ul = claim_element(div7_nodes, "UL", {});
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", {});
			var li0_nodes = children(li0);
			strong0 = claim_element(li0_nodes, "STRONG", {});
			var strong0_nodes = children(strong0);
			t7 = claim_text(strong0_nodes, "Category");
			strong0_nodes.forEach(detach);
			t8 = claim_text(li0_nodes, ": Web design");
			li0_nodes.forEach(detach);
			t9 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", {});
			var li1_nodes = children(li1);
			strong1 = claim_element(li1_nodes, "STRONG", {});
			var strong1_nodes = children(strong1);
			t10 = claim_text(strong1_nodes, "Client");
			strong1_nodes.forEach(detach);
			t11 = claim_text(li1_nodes, ": ASU Company");
			li1_nodes.forEach(detach);
			t12 = claim_space(ul_nodes);
			li2 = claim_element(ul_nodes, "LI", {});
			var li2_nodes = children(li2);
			strong2 = claim_element(li2_nodes, "STRONG", {});
			var strong2_nodes = children(strong2);
			t13 = claim_text(strong2_nodes, "Project date");
			strong2_nodes.forEach(detach);
			t14 = claim_text(li2_nodes, ": 01 March, 2020");
			li2_nodes.forEach(detach);
			t15 = claim_space(ul_nodes);
			li3 = claim_element(ul_nodes, "LI", {});
			var li3_nodes = children(li3);
			strong3 = claim_element(li3_nodes, "STRONG", {});
			var strong3_nodes = children(strong3);
			t16 = claim_text(strong3_nodes, "Project URL");
			strong3_nodes.forEach(detach);
			t17 = claim_text(li3_nodes, ": ");
			a = claim_element(li3_nodes, "A", { href: true });
			var a_nodes = children(a);
			t18 = claim_text(a_nodes, "www.example.com");
			a_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			t19 = claim_space(div9_nodes);
			div8 = claim_element(div9_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);
			h2 = claim_element(div8_nodes, "H2", {});
			var h2_nodes = children(h2);
			t20 = claim_text(h2_nodes, "This is an example of portfolio detail");
			h2_nodes.forEach(detach);
			t21 = claim_space(div8_nodes);
			p = claim_element(div8_nodes, "P", {});
			var p_nodes = children(p);
			t22 = claim_text(p_nodes, "Autem ipsum nam porro corporis rerum. Quis eos dolorem eos itaque inventore commodi labore quia quia. Exercitationem repudiandae officiis neque suscipit non officia eaque itaque enim. Voluptatem officia accusantium nesciunt est omnis tempora consectetur dignissimos. Sequi nulla at esse enim cum deserunt eius.");
			p_nodes.forEach(detach);
			div8_nodes.forEach(detach);
			div9_nodes.forEach(detach);
			div10_nodes.forEach(detach);
			div11_nodes.forEach(detach);
			section_nodes.forEach(detach);
			main_nodes.forEach(detach);
			this.h();
		},
		h() {
			if (img0.src !== (img0_src_value = "assets/img/portfolio/portfolio-details-1.jpg")) attr(img0, "src", img0_src_value);
			attr(img0, "alt", "");
			attr(div0, "class", "swiper-slide");
			if (img1.src !== (img1_src_value = "assets/img/portfolio/portfolio-details-2.jpg")) attr(img1, "src", img1_src_value);
			attr(img1, "alt", "");
			attr(div1, "class", "swiper-slide");
			if (img2.src !== (img2_src_value = "assets/img/portfolio/portfolio-details-3.jpg")) attr(img2, "src", img2_src_value);
			attr(img2, "alt", "");
			attr(div2, "class", "swiper-slide");
			attr(div3, "class", "swiper-wrapper align-items-center");
			attr(div4, "class", "swiper-pagination");
			attr(div5, "class", "portfolio-details-slider swiper");
			attr(div6, "class", "col-lg-8");
			attr(a, "href", "#");
			attr(div7, "class", "portfolio-info");
			attr(div8, "class", "portfolio-description");
			attr(div9, "class", "col-lg-4");
			attr(div10, "class", "row gy-4");
			attr(div11, "class", "container");
			attr(section, "id", "portfolio-details");
			attr(section, "class", "portfolio-details");
		},
		m(target, anchor) {
			insert(target, main, anchor);
			mount_component(breadcrumbs, main, null);
			append(main, t0);
			append(main, section);
			append(section, div11);
			append(div11, div10);
			append(div10, div6);
			append(div6, div5);
			append(div5, div3);
			append(div3, div0);
			append(div0, img0);
			append(div3, t1);
			append(div3, div1);
			append(div1, img1);
			append(div3, t2);
			append(div3, div2);
			append(div2, img2);
			append(div5, t3);
			append(div5, div4);
			append(div10, t4);
			append(div10, div9);
			append(div9, div7);
			append(div7, h3);
			append(h3, t5);
			append(div7, t6);
			append(div7, ul);
			append(ul, li0);
			append(li0, strong0);
			append(strong0, t7);
			append(li0, t8);
			append(ul, t9);
			append(ul, li1);
			append(li1, strong1);
			append(strong1, t10);
			append(li1, t11);
			append(ul, t12);
			append(ul, li2);
			append(li2, strong2);
			append(strong2, t13);
			append(li2, t14);
			append(ul, t15);
			append(ul, li3);
			append(li3, strong3);
			append(strong3, t16);
			append(li3, t17);
			append(li3, a);
			append(a, t18);
			append(div9, t19);
			append(div9, div8);
			append(div8, h2);
			append(h2, t20);
			append(div8, t21);
			append(div8, p);
			append(p, t22);
			current = true;
		},
		p(ctx, [dirty]) {
			if (!current || dirty & /*title*/ 1) set_data(t5, /*title*/ ctx[0]);
		},
		i(local) {
			if (current) return;
			transition_in(breadcrumbs.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(breadcrumbs.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(main);
			destroy_component(breadcrumbs);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { title } = $$props;

	$$self.$$set = $$props => {
		if ("title" in $$props) $$invalidate(0, title = $$props.title);
	};

	return [title];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { title: 0 });
	}
}

export default Component;