/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div6;
	let div5;
	let div0;
	let img;
	let img_src_value;
	let t0;
	let div4;
	let h3;
	let t1;
	let t2;
	let p0;
	let t3;
	let t4;
	let div1;
	let i0;
	let t5;
	let h40;
	let t6;
	let t7;
	let p1;
	let t8;
	let t9;
	let div2;
	let i1;
	let t10;
	let h41;
	let t11;
	let t12;
	let p2;
	let t13;
	let t14;
	let div3;
	let i2;
	let t15;
	let h42;
	let t16;
	let t17;
	let p3;
	let t18;

	return {
		c() {
			section = element("section");
			div6 = element("div");
			div5 = element("div");
			div0 = element("div");
			img = element("img");
			t0 = space();
			div4 = element("div");
			h3 = element("h3");
			t1 = text("Voluptatem dignissimos provident");
			t2 = space();
			p0 = element("p");
			t3 = text("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
			t4 = space();
			div1 = element("div");
			i0 = element("i");
			t5 = space();
			h40 = element("h4");
			t6 = text("Corporis voluptates sit");
			t7 = space();
			p1 = element("p");
			t8 = text("Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip");
			t9 = space();
			div2 = element("div");
			i1 = element("i");
			t10 = space();
			h41 = element("h4");
			t11 = text("Ullamco laboris nisi");
			t12 = space();
			p2 = element("p");
			t13 = text("Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt");
			t14 = space();
			div3 = element("div");
			i2 = element("i");
			t15 = space();
			h42 = element("h4");
			t16 = text("Ullamco laboris nisi");
			t17 = space();
			p3 = element("p");
			t18 = text("Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div6 = claim_element(section_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			div5 = claim_element(div6_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div0 = claim_element(div5_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			img = claim_element(div0_nodes, "IMG", { src: true, class: true, alt: true });
			div0_nodes.forEach(detach);
			t0 = claim_space(div5_nodes);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			h3 = claim_element(div4_nodes, "H3", { "data-aos": true });
			var h3_nodes = children(h3);
			t1 = claim_text(h3_nodes, "Voluptatem dignissimos provident");
			h3_nodes.forEach(detach);
			t2 = claim_space(div4_nodes);
			p0 = claim_element(div4_nodes, "P", { "data-aos": true });
			var p0_nodes = children(p0);
			t3 = claim_text(p0_nodes, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.");
			p0_nodes.forEach(detach);
			t4 = claim_space(div4_nodes);
			div1 = claim_element(div4_nodes, "DIV", { class: true, "data-aos": true });
			var div1_nodes = children(div1);
			i0 = claim_element(div1_nodes, "I", { class: true });
			children(i0).forEach(detach);
			t5 = claim_space(div1_nodes);
			h40 = claim_element(div1_nodes, "H4", {});
			var h40_nodes = children(h40);
			t6 = claim_text(h40_nodes, "Corporis voluptates sit");
			h40_nodes.forEach(detach);
			t7 = claim_space(div1_nodes);
			p1 = claim_element(div1_nodes, "P", {});
			var p1_nodes = children(p1);
			t8 = claim_text(p1_nodes, "Consequuntur sunt aut quasi enim aliquam quae harum pariatur laboris nisi ut aliquip");
			p1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t9 = claim_space(div4_nodes);

			div2 = claim_element(div4_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div2_nodes = children(div2);
			i1 = claim_element(div2_nodes, "I", { class: true });
			children(i1).forEach(detach);
			t10 = claim_space(div2_nodes);
			h41 = claim_element(div2_nodes, "H4", {});
			var h41_nodes = children(h41);
			t11 = claim_text(h41_nodes, "Ullamco laboris nisi");
			h41_nodes.forEach(detach);
			t12 = claim_space(div2_nodes);
			p2 = claim_element(div2_nodes, "P", {});
			var p2_nodes = children(p2);
			t13 = claim_text(p2_nodes, "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt");
			p2_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t14 = claim_space(div4_nodes);

			div3 = claim_element(div4_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div3_nodes = children(div3);
			i2 = claim_element(div3_nodes, "I", { class: true });
			children(i2).forEach(detach);
			t15 = claim_space(div3_nodes);
			h42 = claim_element(div3_nodes, "H4", {});
			var h42_nodes = children(h42);
			t16 = claim_text(h42_nodes, "Ullamco laboris nisi");
			h42_nodes.forEach(detach);
			t17 = claim_space(div3_nodes);
			p3 = claim_element(div3_nodes, "P", {});
			var p3_nodes = children(p3);
			t18 = claim_text(p3_nodes, "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt");
			p3_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			if (img.src !== (img_src_value = "assets/img/about-img.jpg")) attr(img, "src", img_src_value);
			attr(img, "class", "img-fluid");
			attr(img, "alt", "");
			attr(div0, "class", "col-xl-6 col-lg-7");
			attr(div0, "data-aos", "fade-right");
			attr(h3, "data-aos", "fade-up");
			attr(p0, "data-aos", "fade-up");
			attr(i0, "class", "bx bx-receipt");
			attr(div1, "class", "icon-box");
			attr(div1, "data-aos", "fade-up");
			attr(i1, "class", "bx bx-cube-alt");
			attr(div2, "class", "icon-box");
			attr(div2, "data-aos", "fade-up");
			attr(div2, "data-aos-delay", "100");
			attr(i2, "class", "bx bx-cube-alt");
			attr(div3, "class", "icon-box");
			attr(div3, "data-aos", "fade-up");
			attr(div3, "data-aos-delay", "200");
			attr(div4, "class", "col-xl-6 col-lg-5 pt-5 pt-lg-0");
			attr(div5, "class", "row");
			attr(div6, "class", "container");
			attr(section, "id", "about");
			attr(section, "class", "about");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div6);
			append(div6, div5);
			append(div5, div0);
			append(div0, img);
			append(div5, t0);
			append(div5, div4);
			append(div4, h3);
			append(h3, t1);
			append(div4, t2);
			append(div4, p0);
			append(p0, t3);
			append(div4, t4);
			append(div4, div1);
			append(div1, i0);
			append(div1, t5);
			append(div1, h40);
			append(h40, t6);
			append(div1, t7);
			append(div1, p1);
			append(p1, t8);
			append(div4, t9);
			append(div4, div2);
			append(div2, i1);
			append(div2, t10);
			append(div2, h41);
			append(h41, t11);
			append(div2, t12);
			append(div2, p2);
			append(p2, t13);
			append(div4, t14);
			append(div4, div3);
			append(div3, i2);
			append(div3, t15);
			append(div3, h42);
			append(h42, t16);
			append(div3, t17);
			append(div3, p3);
			append(p3, t18);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;