/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	attr,
	children,
	claim_element,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let div;

	return {
		c() {
			div = element("div");
			this.h();
		},
		l(nodes) {
			div = claim_element(nodes, "DIV", { class: true });
			children(div).forEach(detach);
			this.h();
		},
		h() {
			attr(div, "class", "block svelte-jx1gkw");
		},
		m(target, anchor) {
			insert(target, div, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;