/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div1;
	let div0;
	let h2;
	let t0;
	let t1;
	let ol;
	let li0;
	let a0;
	let t2;
	let t3;
	let li1;
	let a1;
	let t4;
	let t5;
	let li2;
	let t6;

	return {
		c() {
			section = element("section");
			div1 = element("div");
			div0 = element("div");
			h2 = element("h2");
			t0 = text("Portfolio Details");
			t1 = space();
			ol = element("ol");
			li0 = element("li");
			a0 = element("a");
			t2 = text("Home");
			t3 = space();
			li1 = element("li");
			a1 = element("a");
			t4 = text("Portfolio");
			t5 = space();
			li2 = element("li");
			t6 = text("Portfolio Details");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { class: true });
			var section_nodes = children(section);
			div1 = claim_element(section_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			div0 = claim_element(div1_nodes, "DIV", { class: true });
			var div0_nodes = children(div0);
			h2 = claim_element(div0_nodes, "H2", {});
			var h2_nodes = children(h2);
			t0 = claim_text(h2_nodes, "Portfolio Details");
			h2_nodes.forEach(detach);
			t1 = claim_space(div0_nodes);
			ol = claim_element(div0_nodes, "OL", {});
			var ol_nodes = children(ol);
			li0 = claim_element(ol_nodes, "LI", {});
			var li0_nodes = children(li0);
			a0 = claim_element(li0_nodes, "A", { href: true });
			var a0_nodes = children(a0);
			t2 = claim_text(a0_nodes, "Home");
			a0_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t3 = claim_space(ol_nodes);
			li1 = claim_element(ol_nodes, "LI", {});
			var li1_nodes = children(li1);
			a1 = claim_element(li1_nodes, "A", { href: true });
			var a1_nodes = children(a1);
			t4 = claim_text(a1_nodes, "Portfolio");
			a1_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t5 = claim_space(ol_nodes);
			li2 = claim_element(ol_nodes, "LI", {});
			var li2_nodes = children(li2);
			t6 = claim_text(li2_nodes, "Portfolio Details");
			li2_nodes.forEach(detach);
			ol_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(a0, "href", "/");
			attr(a1, "href", "/");
			attr(div0, "class", "d-flex justify-content-between align-items-center");
			attr(div1, "class", "container");
			attr(section, "class", "breadcrumbs");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div1);
			append(div1, div0);
			append(div0, h2);
			append(h2, t0);
			append(div0, t1);
			append(div0, ol);
			append(ol, li0);
			append(li0, a0);
			append(a0, t2);
			append(ol, t3);
			append(ol, li1);
			append(li1, a1);
			append(a1, t4);
			append(ol, t5);
			append(ol, li2);
			append(li2, t6);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;