/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	set_style,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div20;
	let div0;
	let h2;
	let t0;
	let t1;
	let p0;
	let t2;
	let t3;
	let div7;
	let div5;
	let div4;
	let div1;
	let i0;
	let t4;
	let h40;
	let t5;
	let t6;
	let p1;
	let t7;
	let t8;
	let div2;
	let i1;
	let t9;
	let h41;
	let t10;
	let t11;
	let p2;
	let t12;
	let t13;
	let div3;
	let i2;
	let t14;
	let h42;
	let t15;
	let t16;
	let p3;
	let t17;
	let t18;
	let div6;
	let iframe;
	let iframe_src_value;
	let t19;
	let div19;
	let div18;
	let form;
	let div10;
	let div8;
	let input0;
	let t20;
	let div9;
	let input1;
	let t21;
	let div11;
	let input2;
	let t22;
	let div12;
	let textarea;
	let t23;
	let div16;
	let div13;
	let t24;
	let t25;
	let div14;
	let t26;
	let div15;
	let t27;
	let t28;
	let div17;
	let button;
	let t29;

	return {
		c() {
			section = element("section");
			div20 = element("div");
			div0 = element("div");
			h2 = element("h2");
			t0 = text("Contact");
			t1 = space();
			p0 = element("p");
			t2 = text("Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			t3 = space();
			div7 = element("div");
			div5 = element("div");
			div4 = element("div");
			div1 = element("div");
			i0 = element("i");
			t4 = space();
			h40 = element("h4");
			t5 = text("Location:");
			t6 = space();
			p1 = element("p");
			t7 = text("A108 Adam Street, New York, NY 535022");
			t8 = space();
			div2 = element("div");
			i1 = element("i");
			t9 = space();
			h41 = element("h4");
			t10 = text("Email:");
			t11 = space();
			p2 = element("p");
			t12 = text("info@example.com");
			t13 = space();
			div3 = element("div");
			i2 = element("i");
			t14 = space();
			h42 = element("h4");
			t15 = text("Call:");
			t16 = space();
			p3 = element("p");
			t17 = text("+1 5589 55488 55s");
			t18 = space();
			div6 = element("div");
			iframe = element("iframe");
			t19 = space();
			div19 = element("div");
			div18 = element("div");
			form = element("form");
			div10 = element("div");
			div8 = element("div");
			input0 = element("input");
			t20 = space();
			div9 = element("div");
			input1 = element("input");
			t21 = space();
			div11 = element("div");
			input2 = element("input");
			t22 = space();
			div12 = element("div");
			textarea = element("textarea");
			t23 = space();
			div16 = element("div");
			div13 = element("div");
			t24 = text("Loading");
			t25 = space();
			div14 = element("div");
			t26 = space();
			div15 = element("div");
			t27 = text("Your message has been sent. Thank you!");
			t28 = space();
			div17 = element("div");
			button = element("button");
			t29 = text("Send Message");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div20 = claim_element(section_nodes, "DIV", { class: true });
			var div20_nodes = children(div20);
			div0 = claim_element(div20_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			h2 = claim_element(div0_nodes, "H2", {});
			var h2_nodes = children(h2);
			t0 = claim_text(h2_nodes, "Contact");
			h2_nodes.forEach(detach);
			t1 = claim_space(div0_nodes);
			p0 = claim_element(div0_nodes, "P", {});
			var p0_nodes = children(p0);
			t2 = claim_text(p0_nodes, "Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			p0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t3 = claim_space(div20_nodes);
			div7 = claim_element(div20_nodes, "DIV", { class: true, "data-aos": true });
			var div7_nodes = children(div7);
			div5 = claim_element(div7_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			div1 = claim_element(div4_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			i0 = claim_element(div1_nodes, "I", { class: true });
			children(i0).forEach(detach);
			t4 = claim_space(div1_nodes);
			h40 = claim_element(div1_nodes, "H4", {});
			var h40_nodes = children(h40);
			t5 = claim_text(h40_nodes, "Location:");
			h40_nodes.forEach(detach);
			t6 = claim_space(div1_nodes);
			p1 = claim_element(div1_nodes, "P", {});
			var p1_nodes = children(p1);
			t7 = claim_text(p1_nodes, "A108 Adam Street, New York, NY 535022");
			p1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t8 = claim_space(div4_nodes);
			div2 = claim_element(div4_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			i1 = claim_element(div2_nodes, "I", { class: true });
			children(i1).forEach(detach);
			t9 = claim_space(div2_nodes);
			h41 = claim_element(div2_nodes, "H4", {});
			var h41_nodes = children(h41);
			t10 = claim_text(h41_nodes, "Email:");
			h41_nodes.forEach(detach);
			t11 = claim_space(div2_nodes);
			p2 = claim_element(div2_nodes, "P", {});
			var p2_nodes = children(p2);
			t12 = claim_text(p2_nodes, "info@example.com");
			p2_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t13 = claim_space(div4_nodes);
			div3 = claim_element(div4_nodes, "DIV", { class: true });
			var div3_nodes = children(div3);
			i2 = claim_element(div3_nodes, "I", { class: true });
			children(i2).forEach(detach);
			t14 = claim_space(div3_nodes);
			h42 = claim_element(div3_nodes, "H4", {});
			var h42_nodes = children(h42);
			t15 = claim_text(h42_nodes, "Call:");
			h42_nodes.forEach(detach);
			t16 = claim_space(div3_nodes);
			p3 = claim_element(div3_nodes, "P", {});
			var p3_nodes = children(p3);
			t17 = claim_text(p3_nodes, "+1 5589 55488 55s");
			p3_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			t18 = claim_space(div7_nodes);
			div6 = claim_element(div7_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);

			iframe = claim_element(div6_nodes, "IFRAME", {
				style: true,
				src: true,
				frameborder: true
			});

			children(iframe).forEach(detach);
			div6_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			t19 = claim_space(div20_nodes);
			div19 = claim_element(div20_nodes, "DIV", { class: true, "data-aos": true });
			var div19_nodes = children(div19);
			div18 = claim_element(div19_nodes, "DIV", { class: true });
			var div18_nodes = children(div18);

			form = claim_element(div18_nodes, "FORM", {
				action: true,
				method: true,
				role: true,
				class: true
			});

			var form_nodes = children(form);
			div10 = claim_element(form_nodes, "DIV", { class: true });
			var div10_nodes = children(div10);
			div8 = claim_element(div10_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);

			input0 = claim_element(div8_nodes, "INPUT", {
				type: true,
				name: true,
				class: true,
				id: true,
				placeholder: true
			});

			div8_nodes.forEach(detach);
			t20 = claim_space(div10_nodes);
			div9 = claim_element(div10_nodes, "DIV", { class: true });
			var div9_nodes = children(div9);

			input1 = claim_element(div9_nodes, "INPUT", {
				type: true,
				class: true,
				name: true,
				id: true,
				placeholder: true
			});

			div9_nodes.forEach(detach);
			div10_nodes.forEach(detach);
			t21 = claim_space(form_nodes);
			div11 = claim_element(form_nodes, "DIV", { class: true });
			var div11_nodes = children(div11);

			input2 = claim_element(div11_nodes, "INPUT", {
				type: true,
				class: true,
				name: true,
				id: true,
				placeholder: true
			});

			div11_nodes.forEach(detach);
			t22 = claim_space(form_nodes);
			div12 = claim_element(form_nodes, "DIV", { class: true });
			var div12_nodes = children(div12);

			textarea = claim_element(div12_nodes, "TEXTAREA", {
				class: true,
				name: true,
				rows: true,
				placeholder: true
			});

			children(textarea).forEach(detach);
			div12_nodes.forEach(detach);
			t23 = claim_space(form_nodes);
			div16 = claim_element(form_nodes, "DIV", { class: true });
			var div16_nodes = children(div16);
			div13 = claim_element(div16_nodes, "DIV", { class: true });
			var div13_nodes = children(div13);
			t24 = claim_text(div13_nodes, "Loading");
			div13_nodes.forEach(detach);
			t25 = claim_space(div16_nodes);
			div14 = claim_element(div16_nodes, "DIV", { class: true });
			children(div14).forEach(detach);
			t26 = claim_space(div16_nodes);
			div15 = claim_element(div16_nodes, "DIV", { class: true });
			var div15_nodes = children(div15);
			t27 = claim_text(div15_nodes, "Your message has been sent. Thank you!");
			div15_nodes.forEach(detach);
			div16_nodes.forEach(detach);
			t28 = claim_space(form_nodes);
			div17 = claim_element(form_nodes, "DIV", { class: true });
			var div17_nodes = children(div17);
			button = claim_element(div17_nodes, "BUTTON", { type: true });
			var button_nodes = children(button);
			t29 = claim_text(button_nodes, "Send Message");
			button_nodes.forEach(detach);
			div17_nodes.forEach(detach);
			form_nodes.forEach(detach);
			div18_nodes.forEach(detach);
			div19_nodes.forEach(detach);
			div20_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "section-title");
			attr(div0, "data-aos", "fade-up");
			attr(i0, "class", "bi bi-geo-alt");
			attr(div1, "class", "address");
			attr(i1, "class", "bi bi-envelope");
			attr(div2, "class", "email mt-4");
			attr(i2, "class", "bi bi-phone");
			attr(div3, "class", "phone mt-4");
			attr(div4, "class", "info");
			attr(div5, "class", "col-lg-5 d-flex align-items-stretch");
			set_style(iframe, "border", "0");
			set_style(iframe, "width", "100%");
			set_style(iframe, "height", "270px");
			if (iframe.src !== (iframe_src_value = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621")) attr(iframe, "src", iframe_src_value);
			attr(iframe, "frameborder", "0");
			iframe.allowFullscreen = true;
			attr(div6, "class", "col-lg-5 d-flex align-items-stretch");
			attr(div7, "class", "row no-gutters justify-content-center");
			attr(div7, "data-aos", "fade-up");
			attr(input0, "type", "text");
			attr(input0, "name", "name");
			attr(input0, "class", "form-control");
			attr(input0, "id", "name");
			attr(input0, "placeholder", "Your Name");
			input0.required = true;
			attr(div8, "class", "col-md-6 form-group");
			attr(input1, "type", "email");
			attr(input1, "class", "form-control");
			attr(input1, "name", "email");
			attr(input1, "id", "email");
			attr(input1, "placeholder", "Your Email");
			input1.required = true;
			attr(div9, "class", "col-md-6 form-group mt-3 mt-md-0");
			attr(div10, "class", "row");
			attr(input2, "type", "text");
			attr(input2, "class", "form-control");
			attr(input2, "name", "subject");
			attr(input2, "id", "subject");
			attr(input2, "placeholder", "Subject");
			input2.required = true;
			attr(div11, "class", "form-group mt-3");
			attr(textarea, "class", "form-control");
			attr(textarea, "name", "message");
			attr(textarea, "rows", "5");
			attr(textarea, "placeholder", "Message");
			textarea.required = true;
			attr(div12, "class", "form-group mt-3");
			attr(div13, "class", "loading");
			attr(div14, "class", "error-message");
			attr(div15, "class", "sent-message");
			attr(div16, "class", "my-3");
			attr(button, "type", "submit");
			attr(div17, "class", "text-center");
			attr(form, "action", "forms/contact.php");
			attr(form, "method", "post");
			attr(form, "role", "form");
			attr(form, "class", "php-email-form");
			attr(div18, "class", "col-lg-10");
			attr(div19, "class", "row mt-5 justify-content-center");
			attr(div19, "data-aos", "fade-up");
			attr(div20, "class", "container");
			attr(section, "id", "contact");
			attr(section, "class", "contact");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div20);
			append(div20, div0);
			append(div0, h2);
			append(h2, t0);
			append(div0, t1);
			append(div0, p0);
			append(p0, t2);
			append(div20, t3);
			append(div20, div7);
			append(div7, div5);
			append(div5, div4);
			append(div4, div1);
			append(div1, i0);
			append(div1, t4);
			append(div1, h40);
			append(h40, t5);
			append(div1, t6);
			append(div1, p1);
			append(p1, t7);
			append(div4, t8);
			append(div4, div2);
			append(div2, i1);
			append(div2, t9);
			append(div2, h41);
			append(h41, t10);
			append(div2, t11);
			append(div2, p2);
			append(p2, t12);
			append(div4, t13);
			append(div4, div3);
			append(div3, i2);
			append(div3, t14);
			append(div3, h42);
			append(h42, t15);
			append(div3, t16);
			append(div3, p3);
			append(p3, t17);
			append(div7, t18);
			append(div7, div6);
			append(div6, iframe);
			append(div20, t19);
			append(div20, div19);
			append(div19, div18);
			append(div18, form);
			append(form, div10);
			append(div10, div8);
			append(div8, input0);
			append(div10, t20);
			append(div10, div9);
			append(div9, input1);
			append(form, t21);
			append(form, div11);
			append(div11, input2);
			append(form, t22);
			append(form, div12);
			append(div12, textarea);
			append(form, t23);
			append(form, div16);
			append(div16, div13);
			append(div13, t24);
			append(div16, t25);
			append(div16, div14);
			append(div16, t26);
			append(div16, div15);
			append(div15, t27);
			append(form, t28);
			append(form, div17);
			append(div17, button);
			append(button, t29);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;