/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div7;
	let div0;
	let h2;
	let t0;
	let t1;
	let p0;
	let t2;
	let t3;
	let div6;
	let ul;
	let li0;
	let i0;
	let t4;
	let a0;
	let t5;
	let i1;
	let i2;
	let t6;
	let div1;
	let p1;
	let t7;
	let t8;
	let li1;
	let i3;
	let t9;
	let a1;
	let t10;
	let i4;
	let i5;
	let t11;
	let div2;
	let p2;
	let t12;
	let t13;
	let li2;
	let i6;
	let t14;
	let a2;
	let t15;
	let i7;
	let i8;
	let t16;
	let div3;
	let p3;
	let t17;
	let t18;
	let li3;
	let i9;
	let t19;
	let a3;
	let t20;
	let i10;
	let i11;
	let t21;
	let div4;
	let p4;
	let t22;
	let t23;
	let li4;
	let i12;
	let t24;
	let a4;
	let t25;
	let i13;
	let i14;
	let t26;
	let div5;
	let p5;
	let t27;

	return {
		c() {
			section = element("section");
			div7 = element("div");
			div0 = element("div");
			h2 = element("h2");
			t0 = text("F.A.Q");
			t1 = space();
			p0 = element("p");
			t2 = text("Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			t3 = space();
			div6 = element("div");
			ul = element("ul");
			li0 = element("li");
			i0 = element("i");
			t4 = space();
			a0 = element("a");
			t5 = text("Non consectetur a erat nam at lectus urna duis? ");
			i1 = element("i");
			i2 = element("i");
			t6 = space();
			div1 = element("div");
			p1 = element("p");
			t7 = text("Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.");
			t8 = space();
			li1 = element("li");
			i3 = element("i");
			t9 = space();
			a1 = element("a");
			t10 = text("Feugiat scelerisque varius morbi enim nunc? ");
			i4 = element("i");
			i5 = element("i");
			t11 = space();
			div2 = element("div");
			p2 = element("p");
			t12 = text("Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.");
			t13 = space();
			li2 = element("li");
			i6 = element("i");
			t14 = space();
			a2 = element("a");
			t15 = text("Dolor sit amet consectetur adipiscing elit? ");
			i7 = element("i");
			i8 = element("i");
			t16 = space();
			div3 = element("div");
			p3 = element("p");
			t17 = text("Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed odio morbi quis");
			t18 = space();
			li3 = element("li");
			i9 = element("i");
			t19 = space();
			a3 = element("a");
			t20 = text("Tempus quam pellentesque nec nam aliquam sem et tortor consequat? ");
			i10 = element("i");
			i11 = element("i");
			t21 = space();
			div4 = element("div");
			p4 = element("p");
			t22 = text("Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in.");
			t23 = space();
			li4 = element("li");
			i12 = element("i");
			t24 = space();
			a4 = element("a");
			t25 = text("Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? ");
			i13 = element("i");
			i14 = element("i");
			t26 = space();
			div5 = element("div");
			p5 = element("p");
			t27 = text("Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque.");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div7 = claim_element(section_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			div0 = claim_element(div7_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			h2 = claim_element(div0_nodes, "H2", {});
			var h2_nodes = children(h2);
			t0 = claim_text(h2_nodes, "F.A.Q");
			h2_nodes.forEach(detach);
			t1 = claim_space(div0_nodes);
			p0 = claim_element(div0_nodes, "P", {});
			var p0_nodes = children(p0);
			t2 = claim_text(p0_nodes, "Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			p0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t3 = claim_space(div7_nodes);
			div6 = claim_element(div7_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			ul = claim_element(div6_nodes, "UL", {});
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", { "data-aos": true });
			var li0_nodes = children(li0);
			i0 = claim_element(li0_nodes, "I", { class: true });
			children(i0).forEach(detach);
			t4 = claim_space(li0_nodes);

			a0 = claim_element(li0_nodes, "A", {
				"data-bs-toggle": true,
				class: true,
				"data-bs-target": true
			});

			var a0_nodes = children(a0);
			t5 = claim_text(a0_nodes, "Non consectetur a erat nam at lectus urna duis? ");
			i1 = claim_element(a0_nodes, "I", { class: true });
			children(i1).forEach(detach);
			i2 = claim_element(a0_nodes, "I", { class: true });
			children(i2).forEach(detach);
			a0_nodes.forEach(detach);
			t6 = claim_space(li0_nodes);

			div1 = claim_element(li0_nodes, "DIV", {
				id: true,
				class: true,
				"data-bs-parent": true
			});

			var div1_nodes = children(div1);
			p1 = claim_element(div1_nodes, "P", {});
			var p1_nodes = children(p1);
			t7 = claim_text(p1_nodes, "Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.");
			p1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t8 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", { "data-aos": true, "data-aos-delay": true });
			var li1_nodes = children(li1);
			i3 = claim_element(li1_nodes, "I", { class: true });
			children(i3).forEach(detach);
			t9 = claim_space(li1_nodes);

			a1 = claim_element(li1_nodes, "A", {
				"data-bs-toggle": true,
				"data-bs-target": true,
				class: true
			});

			var a1_nodes = children(a1);
			t10 = claim_text(a1_nodes, "Feugiat scelerisque varius morbi enim nunc? ");
			i4 = claim_element(a1_nodes, "I", { class: true });
			children(i4).forEach(detach);
			i5 = claim_element(a1_nodes, "I", { class: true });
			children(i5).forEach(detach);
			a1_nodes.forEach(detach);
			t11 = claim_space(li1_nodes);

			div2 = claim_element(li1_nodes, "DIV", {
				id: true,
				class: true,
				"data-bs-parent": true
			});

			var div2_nodes = children(div2);
			p2 = claim_element(div2_nodes, "P", {});
			var p2_nodes = children(p2);
			t12 = claim_text(p2_nodes, "Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.");
			p2_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t13 = claim_space(ul_nodes);
			li2 = claim_element(ul_nodes, "LI", { "data-aos": true, "data-aos-delay": true });
			var li2_nodes = children(li2);
			i6 = claim_element(li2_nodes, "I", { class: true });
			children(i6).forEach(detach);
			t14 = claim_space(li2_nodes);

			a2 = claim_element(li2_nodes, "A", {
				"data-bs-toggle": true,
				"data-bs-target": true,
				class: true
			});

			var a2_nodes = children(a2);
			t15 = claim_text(a2_nodes, "Dolor sit amet consectetur adipiscing elit? ");
			i7 = claim_element(a2_nodes, "I", { class: true });
			children(i7).forEach(detach);
			i8 = claim_element(a2_nodes, "I", { class: true });
			children(i8).forEach(detach);
			a2_nodes.forEach(detach);
			t16 = claim_space(li2_nodes);

			div3 = claim_element(li2_nodes, "DIV", {
				id: true,
				class: true,
				"data-bs-parent": true
			});

			var div3_nodes = children(div3);
			p3 = claim_element(div3_nodes, "P", {});
			var p3_nodes = children(p3);
			t17 = claim_text(p3_nodes, "Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed odio morbi quis");
			p3_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			li2_nodes.forEach(detach);
			t18 = claim_space(ul_nodes);
			li3 = claim_element(ul_nodes, "LI", { "data-aos": true, "data-aos-delay": true });
			var li3_nodes = children(li3);
			i9 = claim_element(li3_nodes, "I", { class: true });
			children(i9).forEach(detach);
			t19 = claim_space(li3_nodes);

			a3 = claim_element(li3_nodes, "A", {
				"data-bs-toggle": true,
				"data-bs-target": true,
				class: true
			});

			var a3_nodes = children(a3);
			t20 = claim_text(a3_nodes, "Tempus quam pellentesque nec nam aliquam sem et tortor consequat? ");
			i10 = claim_element(a3_nodes, "I", { class: true });
			children(i10).forEach(detach);
			i11 = claim_element(a3_nodes, "I", { class: true });
			children(i11).forEach(detach);
			a3_nodes.forEach(detach);
			t21 = claim_space(li3_nodes);

			div4 = claim_element(li3_nodes, "DIV", {
				id: true,
				class: true,
				"data-bs-parent": true
			});

			var div4_nodes = children(div4);
			p4 = claim_element(div4_nodes, "P", {});
			var p4_nodes = children(p4);
			t22 = claim_text(p4_nodes, "Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in.");
			p4_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			t23 = claim_space(ul_nodes);
			li4 = claim_element(ul_nodes, "LI", { "data-aos": true, "data-aos-delay": true });
			var li4_nodes = children(li4);
			i12 = claim_element(li4_nodes, "I", { class: true });
			children(i12).forEach(detach);
			t24 = claim_space(li4_nodes);

			a4 = claim_element(li4_nodes, "A", {
				"data-bs-toggle": true,
				"data-bs-target": true,
				class: true
			});

			var a4_nodes = children(a4);
			t25 = claim_text(a4_nodes, "Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? ");
			i13 = claim_element(a4_nodes, "I", { class: true });
			children(i13).forEach(detach);
			i14 = claim_element(a4_nodes, "I", { class: true });
			children(i14).forEach(detach);
			a4_nodes.forEach(detach);
			t26 = claim_space(li4_nodes);

			div5 = claim_element(li4_nodes, "DIV", {
				id: true,
				class: true,
				"data-bs-parent": true
			});

			var div5_nodes = children(div5);
			p5 = claim_element(div5_nodes, "P", {});
			var p5_nodes = children(p5);
			t27 = claim_text(p5_nodes, "Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque.");
			p5_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			li4_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "section-title");
			attr(div0, "data-aos", "fade-up");
			attr(i0, "class", "bx bx-help-circle icon-help");
			attr(i1, "class", "bx bx-chevron-down icon-show");
			attr(i2, "class", "bx bx-chevron-up icon-close");
			attr(a0, "data-bs-toggle", "collapse");
			attr(a0, "class", "collapse");
			attr(a0, "data-bs-target", "#faq-list-1");
			attr(div1, "id", "faq-list-1");
			attr(div1, "class", "collapse show");
			attr(div1, "data-bs-parent", ".faq-list");
			attr(li0, "data-aos", "fade-up");
			attr(i3, "class", "bx bx-help-circle icon-help");
			attr(i4, "class", "bx bx-chevron-down icon-show");
			attr(i5, "class", "bx bx-chevron-up icon-close");
			attr(a1, "data-bs-toggle", "collapse");
			attr(a1, "data-bs-target", "#faq-list-2");
			attr(a1, "class", "collapsed");
			attr(div2, "id", "faq-list-2");
			attr(div2, "class", "collapse");
			attr(div2, "data-bs-parent", ".faq-list");
			attr(li1, "data-aos", "fade-up");
			attr(li1, "data-aos-delay", "100");
			attr(i6, "class", "bx bx-help-circle icon-help");
			attr(i7, "class", "bx bx-chevron-down icon-show");
			attr(i8, "class", "bx bx-chevron-up icon-close");
			attr(a2, "data-bs-toggle", "collapse");
			attr(a2, "data-bs-target", "#faq-list-3");
			attr(a2, "class", "collapsed");
			attr(div3, "id", "faq-list-3");
			attr(div3, "class", "collapse");
			attr(div3, "data-bs-parent", ".faq-list");
			attr(li2, "data-aos", "fade-up");
			attr(li2, "data-aos-delay", "200");
			attr(i9, "class", "bx bx-help-circle icon-help");
			attr(i10, "class", "bx bx-chevron-down icon-show");
			attr(i11, "class", "bx bx-chevron-up icon-close");
			attr(a3, "data-bs-toggle", "collapse");
			attr(a3, "data-bs-target", "#faq-list-4");
			attr(a3, "class", "collapsed");
			attr(div4, "id", "faq-list-4");
			attr(div4, "class", "collapse");
			attr(div4, "data-bs-parent", ".faq-list");
			attr(li3, "data-aos", "fade-up");
			attr(li3, "data-aos-delay", "300");
			attr(i12, "class", "bx bx-help-circle icon-help");
			attr(i13, "class", "bx bx-chevron-down icon-show");
			attr(i14, "class", "bx bx-chevron-up icon-close");
			attr(a4, "data-bs-toggle", "collapse");
			attr(a4, "data-bs-target", "#faq-list-5");
			attr(a4, "class", "collapsed");
			attr(div5, "id", "faq-list-5");
			attr(div5, "class", "collapse");
			attr(div5, "data-bs-parent", ".faq-list");
			attr(li4, "data-aos", "fade-up");
			attr(li4, "data-aos-delay", "400");
			attr(div6, "class", "faq-list");
			attr(div7, "class", "container");
			attr(section, "id", "faq");
			attr(section, "class", "faq section-bg");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div7);
			append(div7, div0);
			append(div0, h2);
			append(h2, t0);
			append(div0, t1);
			append(div0, p0);
			append(p0, t2);
			append(div7, t3);
			append(div7, div6);
			append(div6, ul);
			append(ul, li0);
			append(li0, i0);
			append(li0, t4);
			append(li0, a0);
			append(a0, t5);
			append(a0, i1);
			append(a0, i2);
			append(li0, t6);
			append(li0, div1);
			append(div1, p1);
			append(p1, t7);
			append(ul, t8);
			append(ul, li1);
			append(li1, i3);
			append(li1, t9);
			append(li1, a1);
			append(a1, t10);
			append(a1, i4);
			append(a1, i5);
			append(li1, t11);
			append(li1, div2);
			append(div2, p2);
			append(p2, t12);
			append(ul, t13);
			append(ul, li2);
			append(li2, i6);
			append(li2, t14);
			append(li2, a2);
			append(a2, t15);
			append(a2, i7);
			append(a2, i8);
			append(li2, t16);
			append(li2, div3);
			append(div3, p3);
			append(p3, t17);
			append(ul, t18);
			append(ul, li3);
			append(li3, i9);
			append(li3, t19);
			append(li3, a3);
			append(a3, t20);
			append(a3, i10);
			append(a3, i11);
			append(li3, t21);
			append(li3, div4);
			append(div4, p4);
			append(p4, t22);
			append(ul, t23);
			append(ul, li4);
			append(li4, i12);
			append(li4, t24);
			append(li4, a4);
			append(a4, t25);
			append(a4, i13);
			append(a4, i14);
			append(li4, t26);
			append(li4, div5);
			append(div5, p5);
			append(p5, t27);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;