/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div8;
	let div7;
	let div0;
	let ul;
	let li0;
	let a0;
	let h40;
	let t0;
	let t1;
	let p0;
	let t2;
	let t3;
	let li1;
	let a1;
	let h41;
	let t4;
	let t5;
	let p1;
	let t6;
	let t7;
	let li2;
	let a2;
	let h42;
	let t8;
	let t9;
	let p2;
	let t10;
	let t11;
	let li3;
	let a3;
	let h43;
	let t12;
	let t13;
	let p3;
	let t14;
	let t15;
	let div6;
	let div5;
	let div1;
	let figure0;
	let img0;
	let img0_src_value;
	let t16;
	let div2;
	let figure1;
	let img1;
	let img1_src_value;
	let t17;
	let div3;
	let figure2;
	let img2;
	let img2_src_value;
	let t18;
	let div4;
	let figure3;
	let img3;
	let img3_src_value;

	return {
		c() {
			section = element("section");
			div8 = element("div");
			div7 = element("div");
			div0 = element("div");
			ul = element("ul");
			li0 = element("li");
			a0 = element("a");
			h40 = element("h4");
			t0 = text("Modi sit est");
			t1 = space();
			p0 = element("p");
			t2 = text("Quis excepturi porro totam sint earum quo nulla perspiciatis eius.");
			t3 = space();
			li1 = element("li");
			a1 = element("a");
			h41 = element("h4");
			t4 = text("Unde praesentium sed");
			t5 = space();
			p1 = element("p");
			t6 = text("Voluptas vel esse repudiandae quo excepturi.");
			t7 = space();
			li2 = element("li");
			a2 = element("a");
			h42 = element("h4");
			t8 = text("Pariatur explicabo vel");
			t9 = space();
			p2 = element("p");
			t10 = text("Velit veniam ipsa sit nihil blanditiis mollitia natus.");
			t11 = space();
			li3 = element("li");
			a3 = element("a");
			h43 = element("h4");
			t12 = text("Nostrum qui quasi");
			t13 = space();
			p3 = element("p");
			t14 = text("Ratione hic sapiente nostrum doloremque illum nulla praesentium id");
			t15 = space();
			div6 = element("div");
			div5 = element("div");
			div1 = element("div");
			figure0 = element("figure");
			img0 = element("img");
			t16 = space();
			div2 = element("div");
			figure1 = element("figure");
			img1 = element("img");
			t17 = space();
			div3 = element("div");
			figure2 = element("figure");
			img2 = element("img");
			t18 = space();
			div4 = element("div");
			figure3 = element("figure");
			img3 = element("img");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div8 = claim_element(section_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);
			div7 = claim_element(div8_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			div0 = claim_element(div7_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			ul = claim_element(div0_nodes, "UL", { class: true });
			var ul_nodes = children(ul);
			li0 = claim_element(ul_nodes, "LI", { class: true });
			var li0_nodes = children(li0);

			a0 = claim_element(li0_nodes, "A", {
				class: true,
				"data-bs-toggle": true,
				href: true
			});

			var a0_nodes = children(a0);
			h40 = claim_element(a0_nodes, "H4", {});
			var h40_nodes = children(h40);
			t0 = claim_text(h40_nodes, "Modi sit est");
			h40_nodes.forEach(detach);
			t1 = claim_space(a0_nodes);
			p0 = claim_element(a0_nodes, "P", {});
			var p0_nodes = children(p0);
			t2 = claim_text(p0_nodes, "Quis excepturi porro totam sint earum quo nulla perspiciatis eius.");
			p0_nodes.forEach(detach);
			a0_nodes.forEach(detach);
			li0_nodes.forEach(detach);
			t3 = claim_space(ul_nodes);
			li1 = claim_element(ul_nodes, "LI", { class: true });
			var li1_nodes = children(li1);

			a1 = claim_element(li1_nodes, "A", {
				class: true,
				"data-bs-toggle": true,
				href: true
			});

			var a1_nodes = children(a1);
			h41 = claim_element(a1_nodes, "H4", {});
			var h41_nodes = children(h41);
			t4 = claim_text(h41_nodes, "Unde praesentium sed");
			h41_nodes.forEach(detach);
			t5 = claim_space(a1_nodes);
			p1 = claim_element(a1_nodes, "P", {});
			var p1_nodes = children(p1);
			t6 = claim_text(p1_nodes, "Voluptas vel esse repudiandae quo excepturi.");
			p1_nodes.forEach(detach);
			a1_nodes.forEach(detach);
			li1_nodes.forEach(detach);
			t7 = claim_space(ul_nodes);
			li2 = claim_element(ul_nodes, "LI", { class: true });
			var li2_nodes = children(li2);

			a2 = claim_element(li2_nodes, "A", {
				class: true,
				"data-bs-toggle": true,
				href: true
			});

			var a2_nodes = children(a2);
			h42 = claim_element(a2_nodes, "H4", {});
			var h42_nodes = children(h42);
			t8 = claim_text(h42_nodes, "Pariatur explicabo vel");
			h42_nodes.forEach(detach);
			t9 = claim_space(a2_nodes);
			p2 = claim_element(a2_nodes, "P", {});
			var p2_nodes = children(p2);
			t10 = claim_text(p2_nodes, "Velit veniam ipsa sit nihil blanditiis mollitia natus.");
			p2_nodes.forEach(detach);
			a2_nodes.forEach(detach);
			li2_nodes.forEach(detach);
			t11 = claim_space(ul_nodes);
			li3 = claim_element(ul_nodes, "LI", { class: true });
			var li3_nodes = children(li3);

			a3 = claim_element(li3_nodes, "A", {
				class: true,
				"data-bs-toggle": true,
				href: true
			});

			var a3_nodes = children(a3);
			h43 = claim_element(a3_nodes, "H4", {});
			var h43_nodes = children(h43);
			t12 = claim_text(h43_nodes, "Nostrum qui quasi");
			h43_nodes.forEach(detach);
			t13 = claim_space(a3_nodes);
			p3 = claim_element(a3_nodes, "P", {});
			var p3_nodes = children(p3);
			t14 = claim_text(p3_nodes, "Ratione hic sapiente nostrum doloremque illum nulla praesentium id");
			p3_nodes.forEach(detach);
			a3_nodes.forEach(detach);
			li3_nodes.forEach(detach);
			ul_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t15 = claim_space(div7_nodes);
			div6 = claim_element(div7_nodes, "DIV", { class: true, "data-aos": true });
			var div6_nodes = children(div6);
			div5 = claim_element(div6_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div1 = claim_element(div5_nodes, "DIV", { class: true, id: true });
			var div1_nodes = children(div1);
			figure0 = claim_element(div1_nodes, "FIGURE", {});
			var figure0_nodes = children(figure0);
			img0 = claim_element(figure0_nodes, "IMG", { src: true, alt: true, class: true });
			figure0_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t16 = claim_space(div5_nodes);
			div2 = claim_element(div5_nodes, "DIV", { class: true, id: true });
			var div2_nodes = children(div2);
			figure1 = claim_element(div2_nodes, "FIGURE", {});
			var figure1_nodes = children(figure1);
			img1 = claim_element(figure1_nodes, "IMG", { src: true, alt: true, class: true });
			figure1_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t17 = claim_space(div5_nodes);
			div3 = claim_element(div5_nodes, "DIV", { class: true, id: true });
			var div3_nodes = children(div3);
			figure2 = claim_element(div3_nodes, "FIGURE", {});
			var figure2_nodes = children(figure2);
			img2 = claim_element(figure2_nodes, "IMG", { src: true, alt: true, class: true });
			figure2_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t18 = claim_space(div5_nodes);
			div4 = claim_element(div5_nodes, "DIV", { class: true, id: true });
			var div4_nodes = children(div4);
			figure3 = claim_element(div4_nodes, "FIGURE", {});
			var figure3_nodes = children(figure3);
			img3 = claim_element(figure3_nodes, "IMG", { src: true, alt: true, class: true });
			figure3_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			div8_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(a0, "class", "nav-link active show");
			attr(a0, "data-bs-toggle", "tab");
			attr(a0, "href", "#tab-1");
			attr(li0, "class", "nav-item");
			attr(a1, "class", "nav-link");
			attr(a1, "data-bs-toggle", "tab");
			attr(a1, "href", "#tab-2");
			attr(li1, "class", "nav-item mt-2");
			attr(a2, "class", "nav-link");
			attr(a2, "data-bs-toggle", "tab");
			attr(a2, "href", "#tab-3");
			attr(li2, "class", "nav-item mt-2");
			attr(a3, "class", "nav-link");
			attr(a3, "data-bs-toggle", "tab");
			attr(a3, "href", "#tab-4");
			attr(li3, "class", "nav-item mt-2");
			attr(ul, "class", "nav nav-tabs flex-column");
			attr(div0, "class", "col-lg-4 mb-5 mb-lg-0");
			attr(div0, "data-aos", "fade-right");
			if (img0.src !== (img0_src_value = "assets/img/features-1.png")) attr(img0, "src", img0_src_value);
			attr(img0, "alt", "");
			attr(img0, "class", "img-fluid");
			attr(div1, "class", "tab-pane active show");
			attr(div1, "id", "tab-1");
			if (img1.src !== (img1_src_value = "assets/img/features-2.png")) attr(img1, "src", img1_src_value);
			attr(img1, "alt", "");
			attr(img1, "class", "img-fluid");
			attr(div2, "class", "tab-pane");
			attr(div2, "id", "tab-2");
			if (img2.src !== (img2_src_value = "assets/img/features-3.png")) attr(img2, "src", img2_src_value);
			attr(img2, "alt", "");
			attr(img2, "class", "img-fluid");
			attr(div3, "class", "tab-pane");
			attr(div3, "id", "tab-3");
			if (img3.src !== (img3_src_value = "assets/img/features-4.png")) attr(img3, "src", img3_src_value);
			attr(img3, "alt", "");
			attr(img3, "class", "img-fluid");
			attr(div4, "class", "tab-pane");
			attr(div4, "id", "tab-4");
			attr(div5, "class", "tab-content");
			attr(div6, "class", "col-lg-7 ml-auto");
			attr(div6, "data-aos", "fade-left");
			attr(div7, "class", "row");
			attr(div8, "class", "container");
			attr(section, "id", "features");
			attr(section, "class", "features");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div8);
			append(div8, div7);
			append(div7, div0);
			append(div0, ul);
			append(ul, li0);
			append(li0, a0);
			append(a0, h40);
			append(h40, t0);
			append(a0, t1);
			append(a0, p0);
			append(p0, t2);
			append(ul, t3);
			append(ul, li1);
			append(li1, a1);
			append(a1, h41);
			append(h41, t4);
			append(a1, t5);
			append(a1, p1);
			append(p1, t6);
			append(ul, t7);
			append(ul, li2);
			append(li2, a2);
			append(a2, h42);
			append(h42, t8);
			append(a2, t9);
			append(a2, p2);
			append(p2, t10);
			append(ul, t11);
			append(ul, li3);
			append(li3, a3);
			append(a3, h43);
			append(h43, t12);
			append(a3, t13);
			append(a3, p3);
			append(p3, t14);
			append(div7, t15);
			append(div7, div6);
			append(div6, div5);
			append(div5, div1);
			append(div1, figure0);
			append(figure0, img0);
			append(div5, t16);
			append(div5, div2);
			append(div2, figure1);
			append(figure1, img1);
			append(div5, t17);
			append(div5, div3);
			append(div3, figure2);
			append(figure2, img2);
			append(div5, t18);
			append(div5, div4);
			append(div4, figure3);
			append(figure3, img3);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;