/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div;
	let h1;
	let t0;
	let t1;
	let h2;
	let t2;
	let t3;
	let a;
	let t4;

	return {
		c() {
			section = element("section");
			div = element("div");
			h1 = element("h1");
			t0 = text("Welcome to Maxim");
			t1 = space();
			h2 = element("h2");
			t2 = text("We are team of talented designers making websites with Bootstrap");
			t3 = space();
			a = element("a");
			t4 = text("Get Started");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div = claim_element(section_nodes, "DIV", { class: true, "data-aos": true });
			var div_nodes = children(div);
			h1 = claim_element(div_nodes, "H1", {});
			var h1_nodes = children(h1);
			t0 = claim_text(h1_nodes, "Welcome to Maxim");
			h1_nodes.forEach(detach);
			t1 = claim_space(div_nodes);
			h2 = claim_element(div_nodes, "H2", {});
			var h2_nodes = children(h2);
			t2 = claim_text(h2_nodes, "We are team of talented designers making websites with Bootstrap");
			h2_nodes.forEach(detach);
			t3 = claim_space(div_nodes);
			a = claim_element(div_nodes, "A", { href: true, class: true });
			var a_nodes = children(a);
			t4 = claim_text(a_nodes, "Get Started");
			a_nodes.forEach(detach);
			div_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(a, "href", "#about");
			attr(a, "class", "btn-get-started scrollto");
			attr(div, "class", "container text-center text-md-left");
			attr(div, "data-aos", "fade-up");
			attr(section, "id", "hero");
			attr(section, "class", "d-flex flex-column justify-content-center align-items-center");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div);
			append(div, h1);
			append(h1, t0);
			append(div, t1);
			append(div, h2);
			append(h2, t2);
			append(div, t3);
			append(div, a);
			append(a, t4);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;