/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div14;
	let div0;
	let h2;
	let t0;
	let t1;
	let p0;
	let t2;
	let t3;
	let div13;
	let div3;
	let div2;
	let div1;
	let i0;
	let t4;
	let h40;
	let a0;
	let t5;
	let t6;
	let p1;
	let t7;
	let t8;
	let div6;
	let div5;
	let div4;
	let i1;
	let t9;
	let h41;
	let a1;
	let t10;
	let t11;
	let p2;
	let t12;
	let t13;
	let div9;
	let div8;
	let div7;
	let i2;
	let t14;
	let h42;
	let a2;
	let t15;
	let t16;
	let p3;
	let t17;
	let t18;
	let div12;
	let div11;
	let div10;
	let i3;
	let t19;
	let h43;
	let a3;
	let t20;
	let t21;
	let p4;
	let t22;

	return {
		c() {
			section = element("section");
			div14 = element("div");
			div0 = element("div");
			h2 = element("h2");
			t0 = text("Services");
			t1 = space();
			p0 = element("p");
			t2 = text("Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			t3 = space();
			div13 = element("div");
			div3 = element("div");
			div2 = element("div");
			div1 = element("div");
			i0 = element("i");
			t4 = space();
			h40 = element("h4");
			a0 = element("a");
			t5 = text("Lorem Ipsum");
			t6 = space();
			p1 = element("p");
			t7 = text("Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate");
			t8 = space();
			div6 = element("div");
			div5 = element("div");
			div4 = element("div");
			i1 = element("i");
			t9 = space();
			h41 = element("h4");
			a1 = element("a");
			t10 = text("Sed ut perspiciatis");
			t11 = space();
			p2 = element("p");
			t12 = text("Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla");
			t13 = space();
			div9 = element("div");
			div8 = element("div");
			div7 = element("div");
			i2 = element("i");
			t14 = space();
			h42 = element("h4");
			a2 = element("a");
			t15 = text("Magni Dolores");
			t16 = space();
			p3 = element("p");
			t17 = text("Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim");
			t18 = space();
			div12 = element("div");
			div11 = element("div");
			div10 = element("div");
			i3 = element("i");
			t19 = space();
			h43 = element("h4");
			a3 = element("a");
			t20 = text("Nemo Enim");
			t21 = space();
			p4 = element("p");
			t22 = text("At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div14 = claim_element(section_nodes, "DIV", { class: true });
			var div14_nodes = children(div14);
			div0 = claim_element(div14_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			h2 = claim_element(div0_nodes, "H2", {});
			var h2_nodes = children(h2);
			t0 = claim_text(h2_nodes, "Services");
			h2_nodes.forEach(detach);
			t1 = claim_space(div0_nodes);
			p0 = claim_element(div0_nodes, "P", {});
			var p0_nodes = children(p0);
			t2 = claim_text(p0_nodes, "Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.");
			p0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t3 = claim_space(div14_nodes);
			div13 = claim_element(div14_nodes, "DIV", { class: true });
			var div13_nodes = children(div13);
			div3 = claim_element(div13_nodes, "DIV", { class: true, "data-aos": true });
			var div3_nodes = children(div3);
			div2 = claim_element(div3_nodes, "DIV", { class: true });
			var div2_nodes = children(div2);
			div1 = claim_element(div2_nodes, "DIV", { class: true });
			var div1_nodes = children(div1);
			i0 = claim_element(div1_nodes, "I", { class: true });
			children(i0).forEach(detach);
			div1_nodes.forEach(detach);
			t4 = claim_space(div2_nodes);
			h40 = claim_element(div2_nodes, "H4", { class: true });
			var h40_nodes = children(h40);
			a0 = claim_element(h40_nodes, "A", { href: true });
			var a0_nodes = children(a0);
			t5 = claim_text(a0_nodes, "Lorem Ipsum");
			a0_nodes.forEach(detach);
			h40_nodes.forEach(detach);
			t6 = claim_space(div2_nodes);
			p1 = claim_element(div2_nodes, "P", { class: true });
			var p1_nodes = children(p1);
			t7 = claim_text(p1_nodes, "Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate");
			p1_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t8 = claim_space(div13_nodes);

			div6 = claim_element(div13_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div6_nodes = children(div6);
			div5 = claim_element(div6_nodes, "DIV", { class: true });
			var div5_nodes = children(div5);
			div4 = claim_element(div5_nodes, "DIV", { class: true });
			var div4_nodes = children(div4);
			i1 = claim_element(div4_nodes, "I", { class: true });
			children(i1).forEach(detach);
			div4_nodes.forEach(detach);
			t9 = claim_space(div5_nodes);
			h41 = claim_element(div5_nodes, "H4", { class: true });
			var h41_nodes = children(h41);
			a1 = claim_element(h41_nodes, "A", { href: true });
			var a1_nodes = children(a1);
			t10 = claim_text(a1_nodes, "Sed ut perspiciatis");
			a1_nodes.forEach(detach);
			h41_nodes.forEach(detach);
			t11 = claim_space(div5_nodes);
			p2 = claim_element(div5_nodes, "P", { class: true });
			var p2_nodes = children(p2);
			t12 = claim_text(p2_nodes, "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla");
			p2_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			t13 = claim_space(div13_nodes);

			div9 = claim_element(div13_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div9_nodes = children(div9);
			div8 = claim_element(div9_nodes, "DIV", { class: true });
			var div8_nodes = children(div8);
			div7 = claim_element(div8_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			i2 = claim_element(div7_nodes, "I", { class: true });
			children(i2).forEach(detach);
			div7_nodes.forEach(detach);
			t14 = claim_space(div8_nodes);
			h42 = claim_element(div8_nodes, "H4", { class: true });
			var h42_nodes = children(h42);
			a2 = claim_element(h42_nodes, "A", { href: true });
			var a2_nodes = children(a2);
			t15 = claim_text(a2_nodes, "Magni Dolores");
			a2_nodes.forEach(detach);
			h42_nodes.forEach(detach);
			t16 = claim_space(div8_nodes);
			p3 = claim_element(div8_nodes, "P", { class: true });
			var p3_nodes = children(p3);
			t17 = claim_text(p3_nodes, "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim");
			p3_nodes.forEach(detach);
			div8_nodes.forEach(detach);
			div9_nodes.forEach(detach);
			t18 = claim_space(div13_nodes);

			div12 = claim_element(div13_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div12_nodes = children(div12);
			div11 = claim_element(div12_nodes, "DIV", { class: true });
			var div11_nodes = children(div11);
			div10 = claim_element(div11_nodes, "DIV", { class: true });
			var div10_nodes = children(div10);
			i3 = claim_element(div10_nodes, "I", { class: true });
			children(i3).forEach(detach);
			div10_nodes.forEach(detach);
			t19 = claim_space(div11_nodes);
			h43 = claim_element(div11_nodes, "H4", { class: true });
			var h43_nodes = children(h43);
			a3 = claim_element(h43_nodes, "A", { href: true });
			var a3_nodes = children(a3);
			t20 = claim_text(a3_nodes, "Nemo Enim");
			a3_nodes.forEach(detach);
			h43_nodes.forEach(detach);
			t21 = claim_space(div11_nodes);
			p4 = claim_element(div11_nodes, "P", { class: true });
			var p4_nodes = children(p4);
			t22 = claim_text(p4_nodes, "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum");
			p4_nodes.forEach(detach);
			div11_nodes.forEach(detach);
			div12_nodes.forEach(detach);
			div13_nodes.forEach(detach);
			div14_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "section-title");
			attr(div0, "data-aos", "fade-up");
			attr(i0, "class", "bx bxl-dribbble");
			attr(div1, "class", "icon");
			attr(a0, "href", "");
			attr(h40, "class", "title");
			attr(p1, "class", "description");
			attr(div2, "class", "icon-box icon-box-pink");
			attr(div3, "class", "col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0");
			attr(div3, "data-aos", "fade-up");
			attr(i1, "class", "bx bx-file");
			attr(div4, "class", "icon");
			attr(a1, "href", "");
			attr(h41, "class", "title");
			attr(p2, "class", "description");
			attr(div5, "class", "icon-box icon-box-cyan");
			attr(div6, "class", "col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0");
			attr(div6, "data-aos", "fade-up");
			attr(div6, "data-aos-delay", "100");
			attr(i2, "class", "bx bx-tachometer");
			attr(div7, "class", "icon");
			attr(a2, "href", "");
			attr(h42, "class", "title");
			attr(p3, "class", "description");
			attr(div8, "class", "icon-box icon-box-green");
			attr(div9, "class", "col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0");
			attr(div9, "data-aos", "fade-up");
			attr(div9, "data-aos-delay", "200");
			attr(i3, "class", "bx bx-world");
			attr(div10, "class", "icon");
			attr(a3, "href", "");
			attr(h43, "class", "title");
			attr(p4, "class", "description");
			attr(div11, "class", "icon-box icon-box-blue");
			attr(div12, "class", "col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0");
			attr(div12, "data-aos", "fade-up");
			attr(div12, "data-aos-delay", "300");
			attr(div13, "class", "row");
			attr(div14, "class", "container");
			attr(section, "id", "services");
			attr(section, "class", "services section-bg");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div14);
			append(div14, div0);
			append(div0, h2);
			append(h2, t0);
			append(div0, t1);
			append(div0, p0);
			append(p0, t2);
			append(div14, t3);
			append(div14, div13);
			append(div13, div3);
			append(div3, div2);
			append(div2, div1);
			append(div1, i0);
			append(div2, t4);
			append(div2, h40);
			append(h40, a0);
			append(a0, t5);
			append(div2, t6);
			append(div2, p1);
			append(p1, t7);
			append(div13, t8);
			append(div13, div6);
			append(div6, div5);
			append(div5, div4);
			append(div4, i1);
			append(div5, t9);
			append(div5, h41);
			append(h41, a1);
			append(a1, t10);
			append(div5, t11);
			append(div5, p2);
			append(p2, t12);
			append(div13, t13);
			append(div13, div9);
			append(div9, div8);
			append(div8, div7);
			append(div7, i2);
			append(div8, t14);
			append(div8, h42);
			append(h42, a2);
			append(a2, t15);
			append(div8, t16);
			append(div8, p3);
			append(p3, t17);
			append(div13, t18);
			append(div13, div12);
			append(div12, div11);
			append(div11, div10);
			append(div10, i3);
			append(div11, t19);
			append(div11, h43);
			append(h43, a3);
			append(a3, t20);
			append(div11, t21);
			append(div11, p4);
			append(p4, t22);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;