/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	attr,
	children,
	claim_element,
	claim_space,
	claim_text,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	space,
	text
} from '../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let section;
	let div7;
	let div6;
	let div0;
	let span0;
	let t0;
	let t1;
	let h40;
	let t2;
	let t3;
	let p0;
	let t4;
	let t5;
	let div1;
	let span1;
	let t6;
	let t7;
	let h41;
	let t8;
	let t9;
	let p1;
	let t10;
	let t11;
	let div2;
	let span2;
	let t12;
	let t13;
	let h42;
	let t14;
	let t15;
	let p2;
	let t16;
	let t17;
	let div3;
	let span3;
	let t18;
	let t19;
	let h43;
	let t20;
	let t21;
	let p3;
	let t22;
	let t23;
	let div4;
	let span4;
	let t24;
	let t25;
	let h44;
	let t26;
	let t27;
	let p4;
	let t28;
	let t29;
	let div5;
	let span5;
	let t30;
	let t31;
	let h45;
	let t32;
	let t33;
	let p5;
	let t34;

	return {
		c() {
			section = element("section");
			div7 = element("div");
			div6 = element("div");
			div0 = element("div");
			span0 = element("span");
			t0 = text("01");
			t1 = space();
			h40 = element("h4");
			t2 = text("Lorem Ipsum");
			t3 = space();
			p0 = element("p");
			t4 = text("Ulamco laboris nisi ut aliquip ex ea commodo consequat. Et consectetur ducimus vero placeat");
			t5 = space();
			div1 = element("div");
			span1 = element("span");
			t6 = text("02");
			t7 = space();
			h41 = element("h4");
			t8 = text("Repellat Nihil");
			t9 = space();
			p1 = element("p");
			t10 = text("Dolorem est fugiat occaecati voluptate velit esse. Dicta veritatis dolor quod et vel dire leno para dest");
			t11 = space();
			div2 = element("div");
			span2 = element("span");
			t12 = text("03");
			t13 = space();
			h42 = element("h4");
			t14 = text("Ad ad velit qui");
			t15 = space();
			p2 = element("p");
			t16 = text("Molestiae officiis omnis illo asperiores. Aut doloribus vitae sunt debitis quo vel nam quis");
			t17 = space();
			div3 = element("div");
			span3 = element("span");
			t18 = text("04");
			t19 = space();
			h43 = element("h4");
			t20 = text("Repellendus molestiae");
			t21 = space();
			p3 = element("p");
			t22 = text("Inventore quo sint a sint rerum. Distinctio blanditiis deserunt quod soluta quod nam mider lando casa");
			t23 = space();
			div4 = element("div");
			span4 = element("span");
			t24 = text("05");
			t25 = space();
			h44 = element("h4");
			t26 = text("Sapiente Magnam");
			t27 = space();
			p4 = element("p");
			t28 = text("Vitae dolorem in deleniti ipsum omnis tempore voluptatem. Qui possimus est repellendus est quibusdam");
			t29 = space();
			div5 = element("div");
			span5 = element("span");
			t30 = text("06");
			t31 = space();
			h45 = element("h4");
			t32 = text("Facilis Impedit");
			t33 = space();
			p5 = element("p");
			t34 = text("Quis eum numquam veniam ea voluptatibus voluptas. Excepturi aut nostrum repudiandae voluptatibus corporis sequi");
			this.h();
		},
		l(nodes) {
			section = claim_element(nodes, "SECTION", { id: true, class: true });
			var section_nodes = children(section);
			div7 = claim_element(section_nodes, "DIV", { class: true });
			var div7_nodes = children(div7);
			div6 = claim_element(div7_nodes, "DIV", { class: true });
			var div6_nodes = children(div6);
			div0 = claim_element(div6_nodes, "DIV", { class: true, "data-aos": true });
			var div0_nodes = children(div0);
			span0 = claim_element(div0_nodes, "SPAN", {});
			var span0_nodes = children(span0);
			t0 = claim_text(span0_nodes, "01");
			span0_nodes.forEach(detach);
			t1 = claim_space(div0_nodes);
			h40 = claim_element(div0_nodes, "H4", {});
			var h40_nodes = children(h40);
			t2 = claim_text(h40_nodes, "Lorem Ipsum");
			h40_nodes.forEach(detach);
			t3 = claim_space(div0_nodes);
			p0 = claim_element(div0_nodes, "P", {});
			var p0_nodes = children(p0);
			t4 = claim_text(p0_nodes, "Ulamco laboris nisi ut aliquip ex ea commodo consequat. Et consectetur ducimus vero placeat");
			p0_nodes.forEach(detach);
			div0_nodes.forEach(detach);
			t5 = claim_space(div6_nodes);

			div1 = claim_element(div6_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div1_nodes = children(div1);
			span1 = claim_element(div1_nodes, "SPAN", {});
			var span1_nodes = children(span1);
			t6 = claim_text(span1_nodes, "02");
			span1_nodes.forEach(detach);
			t7 = claim_space(div1_nodes);
			h41 = claim_element(div1_nodes, "H4", {});
			var h41_nodes = children(h41);
			t8 = claim_text(h41_nodes, "Repellat Nihil");
			h41_nodes.forEach(detach);
			t9 = claim_space(div1_nodes);
			p1 = claim_element(div1_nodes, "P", {});
			var p1_nodes = children(p1);
			t10 = claim_text(p1_nodes, "Dolorem est fugiat occaecati voluptate velit esse. Dicta veritatis dolor quod et vel dire leno para dest");
			p1_nodes.forEach(detach);
			div1_nodes.forEach(detach);
			t11 = claim_space(div6_nodes);

			div2 = claim_element(div6_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div2_nodes = children(div2);
			span2 = claim_element(div2_nodes, "SPAN", {});
			var span2_nodes = children(span2);
			t12 = claim_text(span2_nodes, "03");
			span2_nodes.forEach(detach);
			t13 = claim_space(div2_nodes);
			h42 = claim_element(div2_nodes, "H4", {});
			var h42_nodes = children(h42);
			t14 = claim_text(h42_nodes, "Ad ad velit qui");
			h42_nodes.forEach(detach);
			t15 = claim_space(div2_nodes);
			p2 = claim_element(div2_nodes, "P", {});
			var p2_nodes = children(p2);
			t16 = claim_text(p2_nodes, "Molestiae officiis omnis illo asperiores. Aut doloribus vitae sunt debitis quo vel nam quis");
			p2_nodes.forEach(detach);
			div2_nodes.forEach(detach);
			t17 = claim_space(div6_nodes);

			div3 = claim_element(div6_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div3_nodes = children(div3);
			span3 = claim_element(div3_nodes, "SPAN", {});
			var span3_nodes = children(span3);
			t18 = claim_text(span3_nodes, "04");
			span3_nodes.forEach(detach);
			t19 = claim_space(div3_nodes);
			h43 = claim_element(div3_nodes, "H4", {});
			var h43_nodes = children(h43);
			t20 = claim_text(h43_nodes, "Repellendus molestiae");
			h43_nodes.forEach(detach);
			t21 = claim_space(div3_nodes);
			p3 = claim_element(div3_nodes, "P", {});
			var p3_nodes = children(p3);
			t22 = claim_text(p3_nodes, "Inventore quo sint a sint rerum. Distinctio blanditiis deserunt quod soluta quod nam mider lando casa");
			p3_nodes.forEach(detach);
			div3_nodes.forEach(detach);
			t23 = claim_space(div6_nodes);

			div4 = claim_element(div6_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div4_nodes = children(div4);
			span4 = claim_element(div4_nodes, "SPAN", {});
			var span4_nodes = children(span4);
			t24 = claim_text(span4_nodes, "05");
			span4_nodes.forEach(detach);
			t25 = claim_space(div4_nodes);
			h44 = claim_element(div4_nodes, "H4", {});
			var h44_nodes = children(h44);
			t26 = claim_text(h44_nodes, "Sapiente Magnam");
			h44_nodes.forEach(detach);
			t27 = claim_space(div4_nodes);
			p4 = claim_element(div4_nodes, "P", {});
			var p4_nodes = children(p4);
			t28 = claim_text(p4_nodes, "Vitae dolorem in deleniti ipsum omnis tempore voluptatem. Qui possimus est repellendus est quibusdam");
			p4_nodes.forEach(detach);
			div4_nodes.forEach(detach);
			t29 = claim_space(div6_nodes);

			div5 = claim_element(div6_nodes, "DIV", {
				class: true,
				"data-aos": true,
				"data-aos-delay": true
			});

			var div5_nodes = children(div5);
			span5 = claim_element(div5_nodes, "SPAN", {});
			var span5_nodes = children(span5);
			t30 = claim_text(span5_nodes, "06");
			span5_nodes.forEach(detach);
			t31 = claim_space(div5_nodes);
			h45 = claim_element(div5_nodes, "H4", {});
			var h45_nodes = children(h45);
			t32 = claim_text(h45_nodes, "Facilis Impedit");
			h45_nodes.forEach(detach);
			t33 = claim_space(div5_nodes);
			p5 = claim_element(div5_nodes, "P", {});
			var p5_nodes = children(p5);
			t34 = claim_text(p5_nodes, "Quis eum numquam veniam ea voluptatibus voluptas. Excepturi aut nostrum repudiandae voluptatibus corporis sequi");
			p5_nodes.forEach(detach);
			div5_nodes.forEach(detach);
			div6_nodes.forEach(detach);
			div7_nodes.forEach(detach);
			section_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(div0, "class", "col-lg-4 col-md-6 content-item");
			attr(div0, "data-aos", "fade-in");
			attr(div1, "class", "col-lg-4 col-md-6 content-item");
			attr(div1, "data-aos", "fade-in");
			attr(div1, "data-aos-delay", "100");
			attr(div2, "class", "col-lg-4 col-md-6 content-item");
			attr(div2, "data-aos", "fade-in");
			attr(div2, "data-aos-delay", "200");
			attr(div3, "class", "col-lg-4 col-md-6 content-item");
			attr(div3, "data-aos", "fade-in");
			attr(div3, "data-aos-delay", "300");
			attr(div4, "class", "col-lg-4 col-md-6 content-item");
			attr(div4, "data-aos", "fade-in");
			attr(div4, "data-aos-delay", "400");
			attr(div5, "class", "col-lg-4 col-md-6 content-item");
			attr(div5, "data-aos", "fade-in");
			attr(div5, "data-aos-delay", "500");
			attr(div6, "class", "row no-gutters");
			attr(div7, "class", "container");
			attr(section, "id", "steps");
			attr(section, "class", "steps section-bg");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, div7);
			append(div7, div6);
			append(div6, div0);
			append(div0, span0);
			append(span0, t0);
			append(div0, t1);
			append(div0, h40);
			append(h40, t2);
			append(div0, t3);
			append(div0, p0);
			append(p0, t4);
			append(div6, t5);
			append(div6, div1);
			append(div1, span1);
			append(span1, t6);
			append(div1, t7);
			append(div1, h41);
			append(h41, t8);
			append(div1, t9);
			append(div1, p1);
			append(p1, t10);
			append(div6, t11);
			append(div6, div2);
			append(div2, span2);
			append(span2, t12);
			append(div2, t13);
			append(div2, h42);
			append(h42, t14);
			append(div2, t15);
			append(div2, p2);
			append(p2, t16);
			append(div6, t17);
			append(div6, div3);
			append(div3, span3);
			append(span3, t18);
			append(div3, t19);
			append(div3, h43);
			append(h43, t20);
			append(div3, t21);
			append(div3, p3);
			append(p3, t22);
			append(div6, t23);
			append(div6, div4);
			append(div4, span4);
			append(span4, t24);
			append(div4, t25);
			append(div4, h44);
			append(h44, t26);
			append(div4, t27);
			append(div4, p4);
			append(p4, t28);
			append(div6, t29);
			append(div6, div5);
			append(div5, span5);
			append(span5, t30);
			append(div5, t31);
			append(div5, h45);
			append(h45, t32);
			append(div5, t33);
			append(div5, p5);
			append(p5, t34);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component;